source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '10.0'

use_frameworks!
inhibit_all_warnings!
target 'project' do
    use_frameworks!
#    pod 'XExtension'
#    pod 'XCarryOn'
#    pod 'Bugly'
#    pod 'SnapKit'
#    pod 'RxSwift'
#    pod 'RxCocoa'
#    pod 'Alamofire'
#    pod 'MJRefresh'
#    pod 'Kingfisher'
#    pod 'RealmSwift'
#    pod 'AFNetworking'
#    pod 'IQKeyboardManager'
#    pod 'PayMaxLib'
#    pod 'Realm'
#    pod 'Moya',
#    pod 'ViewDeck'
#    pod 'AVOSCloud'
#    pod 'BlocksKit'
#    pod 'CalendarLib'
#    pod 'iOS-Echarts'
#    pod 'SystemServices'
#    pod 'UMengAnalytics'
#    pod 'MWPhotoBrowser'

#    pod 'BaiduMapKit'
#    pod 'GoogleMaps'
#    pod 'GooglePlaces'
#    pod 'AMapNavi'
#    pod 'AMap3DMap'
#    pod 'AMap2DMap' #(2D和3D不能同时使⽤用)
#    pod 'AMapSearch'
#    pod 'AMapLocation'
#    pod 'MOBFoundation'          # 公共库(必须)
#    pod 'ShareSDK2'              # 主模块(必须)
#    pod 'ShareSDK2/Connection'   # 分享&登录链接模块(含所有平台,可选)
#    pod 'ShareSDK2/Connection/WeChat'# 微信(可选)
#    pod 'Pingpp', '~> 2.1.0' #支付集成接口，包括支付宝，微信，银联和苹果
#    pod 'Pingpp/Alipay', '~> 2.1.0'
#    pod 'Pingpp/Wx', '~> 2.1.0'
#    pod 'Pingpp/UnionPay', '~> 2.1.0'
#    pod 'Pingpp/ApplePay', '~> 2.1.0'
end

# Swift 版本声明
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['LightRoute', 'CoreNavigation', 'Kakapo'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
      else
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end
  end
end

post_install do |installer|
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end  
