platform:ios, '8.0'
target 'MyCocoaPods' do
use_frameworks!
pod 'SDWebImage'
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.0'
pod 'WechatOpenSDK'
pod 'Masonry'
pod 'RealmSwift'
pod 'SnapKit'
#以下是我的CocoaPods
#pod 'BaseScrollView'
#pod 'BaseStaticTableView'
#pod 'BaseFillTableViewController'
#pod 'BaseFile'
#pod 'XUtility'
#pod 'XCategory'
#pod 'ObjectDictionary'   #0.1.1
#pod 'BaseCollectionView'
#pod 'BaseTableView'

end
