platform:ios, '8.0'
target 'MyCocoaPods' do
use_frameworks!
pod 'SDWebImage'                                     #网络图片请求                   https://github.com/rs/SDWebImage
pod 'SVProgressHUD', '0.9'                           #提示性信息展示                  https://github.com/SVProgressHUD/SVProgressHUD
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.0'                         #轻量级网络请求                   https://github.com/AFNetworking/AFNetworking
#以下是我的CocoaPods
pod 'GRBNavigationKit'
pod 'MyPageControl'
pod 'NSData+expanded'
pod 'NSDate+expanded'
pod 'NSDictionary+expanded'
pod 'NSMutableArray+expanded'
pod 'NSObject+expanded'
pod 'NSString+expanded'
pod 'SDDataCache'
pod 'UIColor+expanded'
pod 'UIControl+expanded'
pod 'UIImage+expanded'
pod 'UILabel+expanded'
pod 'UIView+expanded'
pod 'UIView+AutoLayout'
#pod 'Foundation'



end
